### ISSUE TITLE
Sending Poll::Pending appears to hang

### ISSUE THREAD

**Issue by jr200** [devashishdxt/tonic-web-wasm-client#17] opened 2022-10-25 21:36 UTC
Hi,

I'm not sure if I'm using this library correctly, so my apologies upfront...  

In the server part of the test-suite, if I change the body of the implementation of the `Stream` trait to include a `Poll::Pending` return value, the client indefinitely hangs.

```rust
impl Stream for MessageStream {
    type Item = Result<EchoResponse, Status>;

    fn poll_next(mut self: Pin<&mut Self>, _: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        self.count += 1;
        if self.count < 3 {
            Poll::Pending
        } else if self.count < 6 {
            Poll::Ready(Some(Ok(EchoResponse {
                message: format!("echo({})", self.message),
            })))

        } else {
            Poll::Ready(None)
        }
    }
}
```

My use-case is my `MessageStream` wraps another which might return `Poll::Pending`. I should add I am also fairly new to rust.

Thanks!

**Comment by devashishdxt** [comment] 2022-10-26 02:03
I this particular example, you need to arrange `wake()` call for the future so that the runtime knows when to poll the future again.

Read Rust [async book](https://rust-lang.github.io/async-book/02_execution/02_future.html) for better understanding.

**Comment by devashishdxt** [comment] 2022-10-28 04:06
@jr200 Can you confirm if your issue is resolved? If yes, we can close this issue. If not, can you provide more details of what you're trying to do?

**Comment by jr200** [comment] 2022-10-29 08:32
Hi @devashishdxt, I've read the async book now (thanks for the recommendation!). I believe the simple test-case works, but I haven't managed to get my use-case working yet, where I am wrapping a `Receiver` in a `Stream`. Although the browser no longer hangs when a `Poll::Pending` is processed, either the messages do not make it through or I appear to get _many_ more messages than I am expecting. 

I am almost definitely still doing something wrong, so I'll try and put together a minimal example and debug it this weekend.

**Comment by jr200** [comment] 2022-10-29 09:39
Had an initial look, and it seems that the server has to send all messages followed by a `Poll::Ready(None)` (close stream) before the client will begin to process the received messages. So in my case where I have essentially an infinite-stream, the client (browser) never begins to process the first message.

**Comment by teddyrendahl** [comment] 2022-10-29 17:25
I'm seeing this as well. My client does not get the stream response until the stream has closed. My server works fine with the Javascript bindings so I don't think the issue is there.

**Comment by devashishdxt** [comment] 2022-10-30 04:49
@teddyrendahl Can you post some sample JS code and your server code for my reference?

**Comment by jr200** [comment] 2022-11-04 09:30
I was also able to get server-side streaming to work using rust/tonic-web and a JS grpc-web implementation. However, this was using grpcwebtext. The grpc-web streaming [page](https://github.com/grpc/grpc-web) says  `Content-type: application/grpc-web+proto` only supports unary calls, while `Content-type: application/grpc-web-text` supports both unary and server-side streaming calls.

Perhaps I was trying to do something that was never possible. Can you confirm this to be the case?

**Comment by devashishdxt** [comment] 2022-11-04 11:01
@jr200 `application/grpc-web-text` is not yet supported on this crate. But, I'd like to implement support for this. For that, can you please share some sample code (server and js-client) that you're using so that I can test this particular usecase?

**Comment by jr200** [comment] 2022-11-04 11:04
Sure - I will create a minimal example tonight and share it here. 

But with regards to my original issue, can you confirm that this crate does not support streaming with `Content-type: application/grpc-web+proto`?

**Comment by jr200** [comment] 2022-11-04 21:27
Hi @devashishdxt, I've put together a minimal example of a rust server exposing a streaming API over gRPC-web (`Content-type: application/grpc-web-text`), and a with a JS/react frontend consuming the stream.

Code is here: [https://github.com/jr200/grpc-web-example](https://github.com/jr200/grpc-web-example).

Please let me know if are any issues...

**Comment by devashishdxt** [comment] 2022-11-07 03:54
> Hi @devashishdxt, I've put together a minimal example of a rust server exposing a streaming API over gRPC-web, and a with a JS/react frontend consuming the stream (`Content-type: application/grpc-web-text`).
> 
> Code is here: https://github.com/jr200/grpc-web-example.
> 
> Please let me know if are any issues...

Thanks for the example. I'll try and add support for this over the weekend.

**Comment by wackazong** [comment] 2022-11-22 23:41
AFAICS this seems to be impossible in WASM. Getting the chunks of a HTTP response as they come in is not supported in `reqwest` and also not in other WASM-compatible HTTP clients.

**Comment by wackazong** [comment] 2022-11-23 08:22
> Seems [seanmonstar/reqwest#1576](https://github.com/seanmonstar/reqwest/pull/1576) would provide that functionality, so in theory it looks like it's possible.

Yes, I think that is what would need to be enabled.

Edit: I just tried [titanous/grpc-web-client#13](https://github.com/titanous/grpc-web-client/pull/13) as a drop-in-replacement for this crate. Server streaming just works.

Great to hear, thanks!

**Comment by wngr** [comment] 2022-11-23 09:47
I think the way forward would be to re-use the whole parsing logic from tonic, and either use `web-sys` directly or via `reqwest` with added stream support.

**Comment by devashishdxt** [comment] 2022-11-23 09:48
I'm already working on this in `next` branch of this repo. Will finish it in a few days.

**Comment by wngr** [comment] 2022-11-23 09:54
Do you plan on re-using the decoding logic from tonic or stick to rolling your own?

**Closed** 2022-11-24 11:00 UTC

**Comment by wngr** [comment] 2022-11-28 21:20
I can confirm it works. Thanks for this!
